jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

# handlebars 설정
handlebars:
  suffix: .html

logging:
  level:
    sql: debug

github:
  client-id: ENC(pZX3ky4LlJA0EaNyjfryTJrrg+wMqS17)
  client-secret: ENC(9B04CF83IGcKbUt225dta7TlLtBclJnvIURo15mlXo2nbqK+0OWhcY1cT67HqutU)
  user-api-url: https://api.github.com/user
  access-token-url: https://github.com/login/oauth/access_token

jwt:
  key: ENC(7t4lhka8WWQ=)

debug: true
---
spring:
  profiles: local

  datasource:
    url: ENC(yAAKfSsndK8iJjvfYMsK/+Lrb9vQfJ//0JQ4sz1ZF5H2ebBOzWYY2glEFb/fjAqg+gVzvRQTd8cfOL3a/rDKl7LLY0rRQ3B+L6cQDN/p6QY=)
    username: ENC(MXeQAanxppo=)
    password: ENC(QQErW0P9WFtyBoyisL9XAw==)

---
spring:
  profiles: real_server

  datasource:
    url: ENC(yAAKfSsndK+Eu2HY/ukPlHwJqG7QpzS5sUdTEWDJrwrhULgVBBYf1bkGkKGwlNScKCZ/xgRknAlZvizzNMhSRjWWEEE4fV/UAO226k+XSyx/ErD43xbFLOfUDNx5Rk4mgENqyMBFHvr9bPUB/N3Y0ZIs9cP7fcSp0Tdadwyfgao=)
    username: ENC(MXeQAanxppo=)
    password: ENC(QQErW0P9WFtyBoyisL9XAw==)