jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

logging:
  level:
    sql: debug

---
spring:
  profiles: local

  datasource:
    url: ENC(BDec5XAPjm1PZVU9+3IkeWtJvf50AWsMLUFjCNIEinUcCnIogDjW3DtGHkS6ztfV16vWVa6io5JUL/5LNJuGBB+EYttfYqf/f2nBMNPcMzo=)
    username: ENC(/DEaWdfpObo=)
    password: ENC(E9hxauGe3BgotYjCaS4O+g==)

---
spring:
  profiles: real_server

  datasource:
    url: ENC(BDec5XAPjm1PZVU9+3IkeWtJvf50AWsMLUFjCNIEinUcCnIogDjW3DtGHkS6ztfV16vWVa6io5JUL/5LNJuGBB+EYttfYqf/f2nBMNPcMzo=)
    username: ENC(SGzp40WhXRiCGoSbBkM1zw==)
    password: ENC(E9hxauGe3BgotYjCaS4O+g==)
